#!/bin/sh
# =============================================================================
# Xcode Cloud — post-clone
# =============================================================================
# PitchAtlas.xcodeproj is generated by XcodeGen and is NOT committed (it's in
# .gitignore). Xcode Cloud clones the repo and then needs a real .xcodeproj to
# resolve and build the scheme, so we generate it here, before the build phase.
#
# The bundled content JSON is committed to Resources/Content, so CI does NOT need
# the web repo or Node — the project just needs to be generated. Refreshing
# content from the web source is a deliberate pre-release step run locally
# (tools/generate-content), not something CI does on every build.
# =============================================================================
set -eu

if ! command -v xcodegen >/dev/null 2>&1; then
  HOMEBREW_NO_AUTO_UPDATE=1 brew install xcodegen
fi

cd "$CI_PRIMARY_REPOSITORY_PATH"
xcodegen generate
echo "post-clone: generated PitchAtlas.xcodeproj"
